#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the cutTheSticks function below.
def cutTheSticks(arr):
    sticks_cut=[]
    while len(arr)!=0:
        arr.sort()
        temp=arr[0]
        for i in range(0,len(arr)):
            arr[i]=arr[i]-temp
        sticks_cut.append(len(arr))
        arr=[x for x in arr if x!=0]
    return sticks_cut
        
            

            
        
        


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = cutTheSticks(arr)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
